version: "3.8"

services:
#  ชื่อเดียวกับ container name ห้ามซ้ำกับ container อื่นที่มี
  flutter-web-prince:
    build: .
    container_name: flutter-web-prince
    ports:
      - "8084:80"
    networks:
      - docker-network

networks:
  docker-network:
    external: true