version: "3.8"

services:
#  ชื่อเดียวกับ container ห้ามซ้ำกับ container อื่น
  flutter-test:
    build: .
    container_name: flutter-test
    ports:
      - "8083:80"
    networks:
      - docker-network

networks:
  docker-network:
    external: true